#!/usr/bin/env ruby

# entrypoint is a special job which SaturnCI invokes upon every single GitHub
# event.

# SaturnCI jobs are wrapped in this #run method so that jobs can be tested and
# the dependencies such as I/O and the SaturnCI SDK can be dependency-injected
# with stubs.
def run(io, error_io, github_event, client)
  # Output the SaturnCI SDK version for diagnostic purposes. For more
  # information on the SaturnCI SDK, visit
  # https://github.com/saturnci/saturnci-sdk.
  io.puts "SaturnCI SDK version: #{SaturnCI::VERSION}"

  # We only want this particular deploy-on-green job to be triggered for the
  # GitHub push event.
  return 0 unless github_event == "push"

  # This protects against the case where the GitHub push is actually a branch
  # deletion.
  return 0 if ENV['DELETED'] == "true"

  # Halt if branch name is missing.
  branch_name = ENV['BRANCH_NAME']
  if branch_name.to_s.empty?
    error_io.puts "BRANCH_NAME env var is required"
    return 1
  end

  # Halt if commit hash is missing.
  commit_hash = ENV['COMMIT_HASH']
  if commit_hash.to_s.empty?
    error_io.puts "COMMIT_HASH env var is required"
    return 1
  end

  commit_message = ENV['COMMIT_MESSAGE']
  author_name = ENV['AUTHOR_NAME']

  io.puts "Branch name: #{branch_name}"
  io.puts "Commit hash: #{commit_hash}"
  io.puts "Commit message: #{commit_message}"
  io.puts "Author name: #{author_name}"

  test_suite_run = SaturnCI::TestSuiteRun.create(
    client: client,
    repository: 'saturnci/book_tracker',
    branch_name: branch_name,
    commit_hash: commit_hash,
    commit_message: commit_message,
    author_name: author_name
  )

  io.puts "Running test suite: #{test_suite_run.url}"
  test_suite_run.wait_for_completion
  io.puts "Tests #{test_suite_run.status.downcase}."

  if test_suite_run.status == "Passed" && branch_name == "main"
    SaturnCI::JobRun.create(
      client: client,
      repository: 'saturnci/book_tracker',
      job_name: 'deploy',
      name: commit_message,
      branch_name: branch_name,
      commit_hash: commit_hash,
      commit_message: commit_message,
      author_name: author_name
    )
  end

  # Returning an exit code of 0 means success.
  0
end

def client
  SaturnCI::Client.new(credentials)
end

def credentials
  # SATURNCI_API_TOKEN is the value of a personal access token from
  # https://app.saturnci.com/user_profile/personal_access_tokens.
  SaturnCI::Credentials.new(
    api_token: ENV.fetch('SATURNCI_API_TOKEN')
  )
end

exit run($stdout, $stderr, ENV['GITHUB_EVENT'], client) if $PROGRAM_NAME == __FILE__
