#!/usr/bin/env ruby

def run(io, error_io, client)
  io.puts "Deployed"
  0
end

def client
  SaturnCI::Client.new(SaturnCI::Credentials.new(
    api_token: ENV.fetch('SATURNCI_API_TOKEN')
  ))
end

exit run($stdout, $stderr, client) if $PROGRAM_NAME == __FILE__
